export * from './Home';
export * from './components/Blog';
export * from './components/Blog/styled-blog';
export * from './components/Hero';
export * from './components/Hero/styled-hero';
export * from './components/Trending';
export * from './components/Trending/styled-trending';
export * from './components';
export * from './styled-home';
